version: "0.3"
services:
    redis_server:
        container_name: redis_server
        hostname: redis
        image: redis:latest
        command: --port 6379
        ports:
            - "6379:6379"
        expose:
            - "6379"
        healthcheck:
            test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
            interval: 5s
            timeout: 5s
            retries: 5
            
    app:
        image: test-case-local
        container_name: app
        command: >
            sh -c "cd ../ &&
                   alembic upgrade head &&
                   cd ./src &&
                   python main.py"
        ports:
            - "8000:8000"
        depends_on:
            postgres:
                condition: "service_healthy"
        working_dir: /usr/src/app/src
        volumes:
            - ./:/usr/src/app
        links:
            - redis_server
            - postgres

    worker:
        image: test-case-local
        container_name: worker
        command:
            - "rq"
            - "worker"
            - "--url"
            - "redis://redis_server:6379"
            - "task_queue"
        depends_on:
            redis_server:
                condition: "service_healthy"
        working_dir: /usr/src/app/src
        volumes:
            - ./:/usr/src/app
    
    postgres:
        container_name: postgres
        image: postgres:bullseye
        environment:
            POSTGRES_DB: "test_db"
            POSTGRES_USER: "usr"
            POSTGRES_PASSWORD: "pwd"
        ports:
            - "5432:5432"
        expose:
            - "5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U usr -d test_db"]
            interval: 5s
            timeout: 5s
            retries: 5